добавляет редакс
htmlacademy-react/1248355-six-cities-12 pull request #8
Opened 2023-03-19 16:55 UTC by AndreyOtin

2023-03-19 20:01 UTC, VishniakovaAlina requested changes

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/near-places/near-places-list/near-places-list.tsx
> +  const { nearOffers } = useAppSelector((state) => state);
const nearOffers = useAppSelector((state) => state.nearOffers);

Вообще чаще всего если ты импортируешь одну переменную приоритетнее писать так

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/near-places/near-places-list/near-places-list.tsx
> +  const { nearOffers } = useAppSelector((state) => state);
Это не ошибка (если что) ))

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/offer-card/offer-card.tsx
> +      onMouseEnter={isCitiesVariant && (() => dispatch(setActiveOffer(offer)))}
выноси в отдельную функцию

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/offer-card/offer-card.tsx
> +  const isCitiesVariant = OfferCardVariant.Cities === variant || undefined;
isCitiesVariant - булевое значение, почему там undefined?

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/offer-card/offer-card.tsx
> +  const isCitiesVariant = OfferCardVariant.Cities === variant || undefined;
true || undefined  - true
false || undefined - false - если undefined в булевое переводить

Для чего тут вообще undefined?

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/offer-card/offer-card.tsx
> +      onMouseEnter={isCitiesVariant && (() => dispatch(setActiveOffer(offer)))}
() => isCitiesVariant  && dispatch(setActiveOffer(offer))

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/offer-card/offer-card.tsx
> +            onClick={() => dispatch(setActiveOffer(offer))}
Это тоже в отдельную функцию

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/offer-card/offer-card.tsx
> +            onClick={() => dispatch(setActiveOffer(offer))}
В идеале сделай одну

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/property/property.tsx
> +  } = activeOffer;
Эту декомпозацию можно перенести когда activeOffer из стора тянешь, я уже писала выше пример

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/components/tabs/tabs.tsx
> +                className={({ isActive }) => (isActive ? 'locations__item-link tabs__item tabs__item--active' : 'locations__item-link tabs__item')}
используй classNames

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/hooks/store.ts
> +const useAppSelector: TypedUseSelectorHook<State> = useSelector;
Типизни тут стор

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/pages/offer-screen/offer-screen.tsx
> +    return null;
точно нужно тут пустой элемент выводить?

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/store/actions.ts
> +const setCityOffers = createAction('setCityOffers');
тип?

2023-03-19 20:01 UTC, VishniakovaAlina commented on project/src/store/index.ts
> +const store = configureStore({ reducer });
ну или тут стор типизни)

2023-03-20 06:14 UTC, AndreyOtin commented on project/src/components/layout/layout.tsx
> +  , [isCityRoute, isFavoritesRoute, isLoginRoute, isRootRoute, offers.length]);
Сделать свой layout и на каждой странице? :
   <Layout className="классы">
      <Header/>
      {children}
      {isFavoritesRoute && <Footer/>}
    </Layout>

2023-03-20 06:21 UTC, AndreyOtin commented on project/src/components/offer-card/offer-card.tsx
> +  const isCitiesVariant = OfferCardVariant.Cities === variant || undefined;
На одной из страниц карточке не нужен обработчик и для того чтобы его не вешать на ней нужно вернуть undefiend. На этом атрибуите стоит реакт тип handler | undefiend. Нам нужно вернуть иммено undefiend.

2023-03-20 06:24 UTC, AndreyOtin commented on project/src/store/actions.ts
> +const setCityOffers = createAction('setCityOffers');
Не передаем ничего в action

2023-03-20 06:33 UTC, AndreyOtin commented on project/src/pages/offer-screen/offer-screen.tsx
> +    return null;
Можно ретерн вообще пропустить по идеи, так как реакт если видит setState по пути ререндера он делает сразу ререндер комонента не идя дальше, с дипатчерами такой же  механизм должно быть. Но если ретерн оставлять то нужен нул обязательно так как тип у компонент : Element | null. На просто return или undefined будет ошибка.

2023-03-20 06:36 UTC, AndreyOtin commented on project/src/components/offer-card/offer-card.tsx
> +      onMouseEnter={isCitiesVariant && (() => dispatch(setActiveOffer(offer)))}
Так не получится судя по всем, ниже коммент)

2023-03-20 06:39 UTC, AndreyOtin commented on project/src/hooks/store.ts
> +const useAppSelector: TypedUseSelectorHook<State> = useSelector;
У меня в reducer тип на initialState весит, сделать явный тут или в другом где ты предлагаещь ниже?

2023-03-20 07:06 UTC, AndreyOtin commented on project/src/components/property/property.tsx
> +  } = activeOffer;
![image](https://user-images.githubusercontent.com/110828265/226269837-cdf96f14-4526-4fb2-8336-dd1591dfb38f.png)

2023-03-20 07:07 UTC, AndreyOtin commented on project/src/components/property/property.tsx
> +  } = activeOffer;
Вынес ниже так как нужна проверка, млм можно по другому?

2023-03-21 04:47 UTC, AndreyOtin commented on project/src/components/tabs/tabs.tsx
> +                className={({ isActive }) => (isActive ? 'locations__item-link tabs__item tabs__item--active' : 'locations__item-link tabs__item')}
Тут исползтзуется специалбная линка NavLink которая отмечает активную линку и передает значение через функцию. Ксли делать через classnames придется тянуть useMatch и делать кучу проверок

2023-03-21 06:08 UTC, AndreyOtin commented on project/src/components/offer-card/offer-card.tsx
> +  const isCitiesVariant = OfferCardVariant.Cities === variant || undefined;
Переименную переменную isCityVariant ->>> isMouseEnterEvent

2023-03-21 06:18 UTC, AndreyOtin commented on project/src/store/index.ts
> +const store = configureStore({ reducer });
Типзню отдельно в  файле store в папке types
![image](https://user-images.githubusercontent.com/110828265/226531401-63b51260-4611-4949-9690-9973e87b62f3.png)

2023-03-21 07:05 UTC, VishniakovaAlina commented on project/src/components/property/property.tsx
> +  } = activeOffer;
Потому что стор нужно типизнуть

2023-03-21 13:09 UTC, VishniakovaAlina commented on project/src/components/layout/layout.tsx
> +  , [isCityRoute, isFavoritesRoute, isLoginRoute, isRootRoute, offers.length]);
оставь как есть)

2023-03-21 13:09 UTC, VishniakovaAlina commented on project/src/hooks/store.ts
> +const useAppSelector: TypedUseSelectorHook<State> = useSelector;
https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-state-type

2023-03-21 13:09 UTC, VishniakovaAlina commented on project/src/pages/offer-screen/offer-screen.tsx
> +    return null;
> Но если ретерн оставлять

Точно он нужен?

2023-03-21 13:09 UTC, VishniakovaAlina commented on project/src/store/index.ts
> +const store = configureStore({ reducer });
https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-state-type

2023-03-21 13:27 UTC, merged